### ISSUE TITLE
Reporting platform locale doesn't work on Windows

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/usage#100]
While looking at Flutter's analytics for our new Windows support I realized that package:usage doesn't report the language of our Windows users. Looking at the package:usage code that's probably due to the fact that Windows doesn't have an env variable `LANG` set: https://github.com/dart-lang/usage/blob/master/lib/src/usage_impl_io.dart#L139

**Comment by devoncarew** [comment]
We should update package:usage to delegate to package:intl, but I believe support for either is blocked on https://github.com/dart-lang/sdk/issues/29126.
