### ISSUE TITLE
Should report operating system version

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/usage#101]
`AnalyticsIO` should report the operating system **version** (e.g. Windows 7, Windows 10, MacOS 10.3, etc).

**Comment by devoncarew** [comment]
@goderbauer, sounds reasonable. I'd accept PRs for this :)

**Comment by devoncarew** [comment]
closing as we're no longer going to actively work on this package (https://github.com/dart-lang/usage/issues/195)
