### ISSUE TITLE
Allow a client to send a custom dimension

### ISSUE THREAD

**Issue by sethladd** [dart-lang/usage#108]
https://support.google.com/analytics/answer/2709828?hl=en

We'd like to send custom dimensions for screens and events. Is there a way to do this with usage?

Thanks!

**Comment by sethladd** [comment]
Ah, maybe "sendRaw" will let us do it.

**Comment by weisong0** [comment]
You can use setSessionValue. But the value will be sent in with every hit unless you clear it. For example:
```dart
// Set value for custom dimension at index 1.
analytics.setSessionValue('cd1', 'Level 1');
```

**Comment by sethladd** [comment]
Ah, thank you!

**Comment by devoncarew** [comment]
@sethladd, is this for the channel name? That should already be sent in the flutter version.

**Comment by sethladd** [comment]
The version has both the channel and git hash. We'd like a custom dimension for _only_ the channel.

See https://github.com/flutter/flutter/issues/10696
