### ISSUE TITLE
Update docs for Google Analytics setup

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/usage#117]
> When you are creating a new property at google analytics make sure to select the mobile app option, not the website option. 

I’m not sure if this is possible anymore. I selected mobile app but then you are forced to create a firebase analytics project?

**Comment by muzuro** [comment]
Does it mean we shouldn`t enable mobile option?

**Comment by vifird** [comment]
@jimmyff Any news? Do we have to create `a firebase analytics project`?  [https://github.com/dart-lang/usage/issues/137](https://github.com/dart-lang/usage/issues/137)

**Comment by devoncarew** [comment]
closing as we're no longer going to actively work on this package (https://github.com/dart-lang/usage/issues/195)
