### ISSUE TITLE
Add an optional `_FYI` key or similar for the persistent properties JSON file

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/usage#122]
If I run into `~/.stagehand` and open it

```json
{
  "firstRun": false,
  "enabled": true,
  "clientId": "XYZ..."
}
```

I may wonder what's going on.

If I saw...
```json
{
  "_FYI": "This file stores Google Analytics settings for https://pub.dartlang.org/packages/stagehand",
  "firstRun": false,
  "enabled": true,
  "clientId": "XYZ..."
}
```
I'd be much less confused...

**Comment by kevmoo** [comment]
Thoughts, @devoncarew ?

**Comment by devoncarew** [comment]
That sounds reasonable. We could also parse and ignore leading `# foo` lines, and generate the file with a comment:

```
# This file stores Google Analytics settings for https://pub.dartlang.org/packages/stagehand.

{
  "firstRun": false,
  "enabled": true,
  "clientId": "XYZ..."
}
```

**Comment by devoncarew** [comment]
Or, just convert it entirely to a `.properties` file...

**Comment by kevmoo** [comment]
Was pondering a solution where we keep backwards compat – and avoid getting
into the parser business...

**Comment by devoncarew** [comment]
closing as we're no longer going to actively work on this package (https://github.com/dart-lang/usage/issues/195)
