### ISSUE TITLE
E-Commerce

### ISSUE THREAD

**Issue by ysoofiyani** [dart-lang/usage#129]
Hi,
I used below code for showing added items to cart on Google Analytics, but I can not see data on parameters section. I don't know my code has issue or I have to create a custom report page on GA. Could you help me???

AppComponent.ga.sendEvent('add_to_cart', 'items',parameters: {
           'id':product.id,
           'sku': product.skuNumber,
           'name': product.name,
           'price': product.price.toString(),
           'quantitiy': proQty.toString()
          });

**Comment by devoncarew** [comment]
Hi, this is a Dart library for access to the analytics hosted API. I think you question is better for something like a support email list of stackoverflow.
