### ISSUE TITLE
Do we need to add Firebase SDK in Flutter APP while using usage?

### ISSUE THREAD

**Issue by lanistor** [dart-lang/usage#137]
As i saw the source code, `usage` library send `HTTP` request  directly, so we don't need to add [Firebase SDK](https://firebase.google.com/docs/ios/setup#frameworks), right?

**Comment by angelo-squadra** [comment]
Any update?

**Comment by ferrarafer** [comment]
@angelo-savioti  No, for what I understand there is no need to add Firebase SDK. Is using only Google Analytics, Firebase is on top of Google Analytics.

**Comment by lanistor** [comment]
> @angelo-savioti No, for what I understand there is no need to add Firebase SDK. Is using only Google Analytics, Firebase is on top of Google Analytics.

Thanks a lot for reply.
