### ISSUE TITLE
No longer works?

### ISSUE THREAD

**Issue by runyaga** [dart-lang/usage#154]
If you create a new Analytics property it wants you to add "Data Streams" choices: iOS, Android or Web.  I could not get any data to show up in realtime analytics without setting up Data Stream.  I can see in flutter observatory that usage is sending requests to analytics.  Alas nothing shows up in realtime tracking.

I then created a Data Stream.   This did not have any affect on usage / Google Analytics.  realtime dashboard did not show any results.

I will nowmove on to trying to use Firebase SDK/Analytics.

**Comment by runyaga** [comment]
Unfortunately I had to use Firebase SDK ;-( Firebase SDK is a giant native platform dependency.  Maybe I needed to use Web "Data Stream" in google analytics and ignore the Android/iOS to get usage working in my Flutter app?  It really would be nice to use a pure dart version and the documentation signals that it will work in Flutter.

**Comment by mr-mmmmore** [comment]
I have managed to use the plugin for a mobile app: 

1. The Google Analytics property must be created as Universal Analytics, the former standard. Use "Show advanced options" to see this setting when creating the property.
2. By default UA properties seem to be able to track only web sites, but this is only a predefined setting that can be changed. This [stackoverflow answer](https://stackoverflow.com/a/46191986) explains how to do it.
