### ISSUE TITLE
UUID in Dart SDK/stdlib

### ISSUE THREAD

**Issue by Daegalus** [dart-lang/usage#180]
Hey, I am the maintainer of the `dart-uuid` package. The more I work on it and the more it's used, the more I think it should be part of the dart stdlib, or a first party package.

I am currently working on a refactor for v4 of the library, which also adds support for UUID v6,v7, and v8 based on the new draft RFC along the already implemented 1, 4, and 5.

Secondly, I became a father almost 6 months ago, and my extra coding time has dwindled, so while I can maintain the library, active development will slow after I land my refactor.

Would the Dart team be amiable if I opened a PR to add uuid as an official package to the stdlib? I feel it's an important functionality that should be present in the stdlib.

I am also ok with just transferring ownership to dart team if that's preferred after I get my refactor branch merged.

Either way, after seeing what happens in the node.js community, I am reluctant to let someone else outside the dart team have ownership. 

So let me know what you think, and I'll adjust accordingly. I can work on a net new implementation that fits better in the design of the stdlib if that is preferred.

Thanks

Repo for reference: https://github.com/Daegalus/dart-uuid
(V4 branch: https://github.com/Daegalus/dart-uuid/tree/uuidv6)

**Comment by Daegalus** [comment]
Sorry, wrong repository

**Comment by devoncarew** [comment]
No worries; though I'm curious where the issue ended up :)

**Comment by Daegalus** [comment]
> No worries; though I'm curious where the issue ended up :)

https://github.com/dart-lang/sdk/issues/49487
