### ISSUE TITLE
Huge output size

### ISSUE THREAD

**Issue by Fox32** [dart-lang/usage#35]
While regularly checking the output size (after dart2js) of your web application, I noticed a big increase. The uncompressed size of our javascript file increased by 400 kb. After compression using gzip it is still 100 kb bigger than before. This is not acceptable for us.

I investigated what this increase is causing: It is the use of the `uuid` package and all it's dependencies. Currently `uuid` is used to generate the unique client id.
Using `uuid` in console applications is fine. Looks like the normal Google Analytics implementation is only using a simple random number as a client id.

I think it would be usefull if the generator for the client id could be set from the outside, or to force the use of a simple random number for the Html version of the library. The client id generator could be a simple callback function or a class as we already have for `PostHandler` and `PersistentProperties`.

**Comment by sethladd** [comment]
Thanks @daegalus !

**Comment by Daegalus** [comment]
I am glad I got it down to a proper size. Sorry for the initial trouble. I am actually surprised it was such a small difference for the simple one you guys implemented, but I won't complain :)!
