### ISSUE TITLE
sendEvent doesn't seem to work for html version

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/usage#56]
I cloned the repo, and tried the examples.
For me, the console apps sends events:

![image](https://cloud.githubusercontent.com/assets/1035299/12061078/68a575f4-af7d-11e5-9cc6-ef6d99514024.png)

But I try the html version, nothing happens, `screenView` does work though

**Comment by kasperpeulen** [comment]
ah, it seems the example needs to include `_analytics.optIn = true`

**Comment by devoncarew** [comment]
Fixed by https://github.com/dart-lang/usage/pull/57.

**Comment by devoncarew** [comment]
And FYI, when I have just needed very simple analytics for web pages, I've used very simple wrappers of the analytics JS: https://github.com/dart-lang/dart-pad/blob/master/lib/src/ga.dart.
