### ISSUE TITLE
Problem in package import version 2.0.0

### ISSUE THREAD

**Issue by andreabozza1984** [dart-lang/usage#69]
Hello, 
 I have imported the version 2.0.0
When i compile my YAML i obtain this error:

[Error from Dart2JS on myprjweb/dart/main.dart]:
packages/usage/usage.dart:27:8:
Expected ';' after this.
import 'src/usage_impl_default.dart'
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Error from Dart2JS on myprjweb/dart/main.dart]:
packages/usage/usage.dart:28:4:
'if' is a reserved word and can't be used here.
Try using a different name.
   if (dart.library.js) 'src/usage_impl_html.dart'
   ^^

See the image below that shown the issue:

<img width="548" alt="screen shot 2016-04-08 at 17 40 32" src="https://cloud.githubusercontent.com/assets/18351962/14389034/09514380-fdb1-11e5-99aa-0ba7bb9e0e3f.png">

Thank you
Andrea

**Comment by devoncarew** [comment]
You'll want to use the 1.x.x version when building with something that doesn't support conditional imports.  Conditional imports will be working their way through the dart toolchain. The 1.x.x. version and the 2.x are functionally identical; 2.x will work better in a Flutter app.
