### ISSUE TITLE
io (and presumably flutter) backend language is missing 100% of the time

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/usage#80]
https://github.com/dart-lang/usage/blob/master/lib/src/usage_impl_io.dart#L52

It's possible we need additional ways to get the current language/locale?
http://superuser.com/questions/392439/lang-and-language-environment-variable-in-debian-based-systems

100% of the analytics reports from flutter_tool are missing language.

FYI @sethladd

**Comment by eseidelGoogle** [comment]
This is intl's method:
https://github.com/dart-lang/intl/blob/master/lib/intl_standalone.dart#L31

**Comment by devoncarew** [comment]
Fixed in https://github.com/dart-lang/usage/pull/92
