### ISSUE TITLE
Please tag published version 2.2.2 in repo

### ISSUE THREAD

**Issue by whesse** [dart-lang/usage#84]
We cannot load this version in sdk/DEPS without a tag.

**Comment by devoncarew** [comment]
I'm curious, who uses v2.2.2?

**Comment by devoncarew** [comment]
done: https://github.com/dart-lang/usage/releases/tag/v2.2.2

**Comment by whesse** [comment]
I'm updating our third_party/pkg packages imported by sdk/DEPS to the latest mutually compatible package versions, and pub upgrade gets that version of package:usage.
