### ISSUE TITLE
publish version 3.0.0 to pub

### ISSUE THREAD

**Issue by lequem** [dart-lang/usage#89]
Hello,

I cannot get the last version (3.0.0) with pub get.
Moreover, the dedicated dart-lang website page of usage refer to the version 2.2.2

Is it normal?

Vincent

**Comment by devoncarew** [comment]
We're working on 3.0.0 on master - that work hasn't yet been released to pub.

I'll change the title of this issue to make it a tracking issue for publishing 3.0.0.
